### PR TITLE
refactor: better parsing for Windows URI

### LINKED ISSUE #7: URL support not working on Mac OS X
Report from @chuckf originally on https://github.com/bwklein/asciidoc-image-helper/issues/20

Using Atom 1.7.3 and asciidoc-image-helper 0.9.2, when I paste a path to an image file that path pastes in and does not convert to an image:: link as expected.

The test path I have used is:

```
/Users/chuckf/Downloads/splunk.png
/Users/chuckf/Downloads/splunk.jpg
```

Expected result is

```
image::splunk.png
image::splunk.jpg
```

Actual result:

```
/Users/chuckf/Downloads/splunk.png
/Users/chuckf/Downloads/splunk.jpg
```

NOTE: When pasting similar paths on a Fedora box, same versions of the software, the URLs are converted to `image:: links` as expected.

I don't get a success or error message popup.

I opened the console window with <kbd>cmd-alt-i</kbd> (for future reference) and did not see any errors occur when pasting in the link.

I typed the paths into a text editor, HTML page, and ran the command `ls /Users/chuckf/Downloads/splunk.png` into the native terminal and iterm2. I then selected the text and copied using <kbd>cmd-c</kbd> and pasted into Atom using <kbd>cmd-v</kbd>.

### PR DESCRIPTION
**Pull request by ldez**
It's a try, because I don't have OSX.

@nicorikken can you validate?

Fix #7

### CODE REVIEW

**Comment by ldez** [comment]
@bwklein can you validate the non regression on Windows?

**Comment by bwklein** [comment]
It doesn't seem to be working for me on Windows as is.  I am looking at it now.

**Comment by ldez** [comment]
Can you give the whole content of the clipboard text ?
`console.log clipboard.readText ()`
With whitespace and new line

**Comment by bwklein** [comment]
I don't know why this didn't commit into this PR, but I made changes that worked for me in both the file:\\ and the quoted path string cases on Windows.

https://github.com/asciidoctor/atom-asciidoc-image-helper/commit/eef31a7e07618d0af281769754ee63ce180cbe0b

**Comment by bwklein** [comment]
I see now, this pull request is from your own fork and not a feature branch in this project.

**Comment by bwklein** [comment]
Note: With Windows, if you copy from a browser a local file path, then you get the file:\\ version without quotes on the string.  If you Shift-rightclick an image and Copy as Path, then you get a quoted path string.  In the first case, you just need to strip the file:\\ part of the string.  In the second case you remove the quotes from around it.

**Pull request closed without merging**
