### PR TITLE
Revert "Commit Changes for Custom Filenames"

### PR DESCRIPTION
**Pull request by ldez**
Reverts asciidoctor/atom-asciidoc-image-helper#5

### CODE REVIEW

**Comment by ldez** [comment]
big mistake... Sorry.
I haven't see the branch name!

**Comment by bwklein** [comment]
@ldez should I push the changes back in, or can you undo this merge to the custom-filenames branch?

**Comment by ldez** [comment]
I undo all.

**Comment by ldez** [comment]
It's fixed.
Sorry.

**Pull request merged**
