### PR TITLE
Commit Changes for Custom Filenames

### PR DESCRIPTION
**Pull request by bwklein**

### CODE REVIEW

**Comment by bwklein** [comment]
I couldn't figure out how to bring the old Pull Request into this project.  So I brought in the changes into my fork of this project and into the custom-filenames branch.  This shouldn't be an issue again in the future now that we have the project moved under the asciidoctor org.

**Comment by ldez** [comment]
merge ?

**Comment by ldez** [comment]
I revert sorry.

**Comment by ldez** [comment]
mistake...

**Pull request merged**
