### PR TITLE
feat: dialog box for custom image name

### LINKED ISSUE #8: Add ability to modify the filename
Original report from @chuckf at: https://github.com/bwklein/asciidoc-image-helper/issues/2

Currently a pasted image uses the name of the doc and a hash as the file name when it is pasted in.
I would like the ability to modify the file name that is used when pasting an image into the document.

My thought would be this is either a pop up dialog box for complete naming flexibility or an option to add a custom field to the file name.

Currently it is  `my_asciidoc_file-56fe6.png`

A custom field might allow me to put my name or other identifier in there for image tracking purposes.

The custom field would make it look something like this `my_asciidoc_file-56fe6-chuck.png`

### PR DESCRIPTION
**Pull request by ldez**
- URL
- native image

capture du 2016-05-26 19-48-19

Fix #8

### CODE REVIEW

**Comment by ldez** [comment]
a bonus :  Place images in folder that is the same as the filename without the extension. #11

**Comment by bwklein** [comment]
You are awesome!  :)
I'll test this and then I think we should merge and release it.

**Comment by bwklein** [comment]
Ok, so the custom filenames feature is working perfectly.  But now URL support is not working on Windows 10.

It is just pasting the `file:`  or the`path` string.

**Comment by ldez** [comment]
Windows hate me today :sob:

**Comment by ldez** [comment]
Can you explain me the problem?

**Comment by bwklein** [comment]
It is like the Image URL support else if method is not working.
I am testing it now to see if it is even being triggered and where it is failing.

Right now the problem is that if I paste either of the two example strings below, the string is pasted instead of the image macro (with all the correct actions with image file handling) as expected.

"C:\Users\Bryan\Pictures\Examples\Ex1_0.png"
or
file:///C:/Users/Bryan/Pictures/Examples/Ex1_0.png

**Comment by ldez** [comment]
the option `customFilenames` is activated?

**Comment by bwklein** [comment]
Yes it was in that test.

**Comment by ldez** [comment]
sorry wrong copy paste: `enableUrlSupport`

**Comment by bwklein** [comment]
I found it, everything is working fine.  I had used an image that had JPG in all caps as the extension and this was not one of the supported file types.  We need to either convert extensions to lower case before checking them in the `isImageUrl` function, or add all caps versions of each supported extension.

**Comment by ldez** [comment]
ok I will fix.

**Comment by bwklein** [comment]
Once that is fixed, I say release this excellent new feature! :+1:

**Comment by ldez** [comment]
Done!

**Pull request merged**
